#!/usr/bin/env bash

# ===== Loading Scripting Additions ============
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ===== Tiling setting =========================

yabai -m config layout                      bsp
yabai -m config window_gap                  20
yabai -m config top_padding                 20
yabai -m config bottom_padding              20
yabai -m config left_padding                20
yabai -m config right_padding               20
# yabai -m config external_bar 		            all:35:0

yabai -m config mouse_follows_focus         on
yabai -m config focus_follows_mouse         on

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config window_border               off
yabai -m config window_border_width         20

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# ===== Rules ==================================
yabai -m rule --add label="系统设置" app="^系统设置$" title=".*" manage=off
yabai -m rule --add label="计算器" app="^计算器$" manage=off

set +x
printf "yabai: configuration loaded...\\n"

